### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sundharsk** [Ravi879/NoticeBoard#1]
![{FE86D9D5-F4CC-4483-9500-4AA203F3C3B7} png](https://user-images.githubusercontent.com/46772827/54178427-c53a0d80-44bb-11e9-8369-a673d8a4e954.jpg)

**Comment by Ravi879** [comment]
I clone the repo & tested, it's working fine. I also updated the repository with new version of [Android-SpinKit 1.2.0](https://github.com/ybq/Android-SpinKit).
Does your build.gradle file includes the  `maven { url "https://jitpack.io" } `  inside the 
` repositories {
        maven { url "https://jitpack.io" }
        google()
        jcenter()
    }`. 

You can find the solution [here](https://github.com/ybq/Android-SpinKit/issues/62) too.

**Comment by sundharsk** [comment]
actually i have imported only that code part .. so i want to know about firebase database whether i have to configure with the db ??

**Comment by Ravi879** [comment]
Yes, you have to create the firebase db manually. It will gives you the goole-service.json file. After the downloading file, you have to paste in "app" folder.

**Comment by sundharsk** [comment]
yes i have imported the google-service.json file but 
![Capture2](https://user-images.githubusercontent.com/46772827/54199493-11eb0c00-44ef-11e9-9d24-ce480015bdbb.PNG)
now i got the kotlin compiler errors

**Comment by sundharsk** [comment]
yes i have imported the google-service.json file but now i got the kotlin compiler errors
![Capture2](https://user-images.githubusercontent.com/46772827/54199551-3646e880-44ef-11e9-8702-c965c2269cc7.PNG)
