### ISSUE TITLE
Yes, you have to create the firebase db manually. It will gives you the goole-service.json file. After the downloading file, you have to paste in "app" folder.

### ISSUE THREAD

**Issue by sundharsk** [Ravi879/NoticeBoard#2]
Yes, you have to create the firebase db manually. It will gives you the goole-service.json file. After the downloading file, you have to paste in "app" folder.

_Originally posted by @Ravi879 in https://github.com/Ravi879/NoticeBoard/issues/1#issuecomment-471956989_

**Comment by sundharsk** [comment]
yes i have imported the google-service.json file but now i got the kotlin compiler errors
![Capture2](https://user-images.githubusercontent.com/46772827/54198955-bff5b680-44ed-11e9-8f75-038093f0c596.PNG)

**Comment by Ravi879** [comment]
Do you update version of any dependency in build.gradle file?
In my case i doesn't get any error. 
Hope you will find the solutions here. 
Below i put some stack links, that not exact solution, but it may help to figure out the problem. Please check it,
[Ide & kotlin issue](https://stackoverflow.com/a/54103099)
[For Bundle & Bundle?](https://stackoverflow.com/a/47051391/9150094)

**Comment by sundharsk** [comment]
yes , I have updated every dependency in build.gradle file .

**Comment by Ravi879** [comment]
**Note :- ** Do not update the any dependency in build.gradle file,  and try to build the project.  You check the above stack links ?

**Comment by sundharsk** [comment]
actually i imported only that code folder whether i should import all  folders

**Comment by Ravi879** [comment]
No, you only need to open the code folder from the Android studio. You still got an error?

**Comment by sundharsk** [comment]
yes , still i am getting  an 
error

**Comment by sundharsk** [comment]
error

![Capture3](https://user-images.githubusercontent.com/46772827/54253320-89af4a00-4574-11e9-884c-d55e55d301e1.PNG)

![cp4](https://user-images.githubusercontent.com/46772827/54254342-633fdd80-4579-11e9-97f5-2e96ba06b966.jpg)
